name: PR Build Check

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/pr-build.yml'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  build:
    name: Build Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Checkout PR Branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          gh pr checkout ${{ github.event.inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: backend/go.sum

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            python/.venv
          key: ${{ runner.os }}-python-${{ hashFiles('python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: npm install
        env:
          PYTHON: ${{ steps.setup_python.outputs.python-path }}

      - name: Verify Python backend can build (skip heavy AI deps for PR)
        run: |
          cd python
          pip install --upgrade pip pyinstaller
          echo "Python backend build verification completed for PR"

      - name: Rebuild native modules for Electron
        run: npm run rebuild
        env:
          DEBUG: 'electron-rebuild'
          PYTHON: ${{ steps.setup_python.outputs.python-path }}

      - name: Create dummy app-config.json
        shell: bash
        run: |
          echo "{
            \"VITE_GOOGLE_CLIENT_ID\": \"DUMMY_PR_BUILD_CLIENT_ID\",
            \"VITE_GOOGLE_CLIENT_SECRET\": \"DUMMY_PR_BUILD_CLIENT_SECRET\"
          }" > app-config.json
          echo "Dummy app-config.json created for PR build."

      - name: Build Release Files (skip Python backend for PR)
        run: npm run build:web && electron-builder --publish never
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Python backend (if previous step failed)
        if: failure()
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr_build_on_${{ matrix.os }}
          path: release/
          retention-days: 3
